### ISSUE TITLE
Log Upload Failed

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/CrashReporter#16]
I've just got a RuntimeException when hit the "upload to pastebin" button. Is that due to the pastebin limit?

```
Exception in thread "Upload" java.lang.RuntimeException: Failed to fetch contents from link: java.io.IOException: Server
 returned HTTP response code: 502 for URL: http://pastebin.com/api/api_post.php
        at org.jpaste.utils.web.Web.getContents(Web.java:59)
        at org.jpaste.pastebin.PastebinPaste.paste(PastebinPaste.java:297)
        at org.terasology.crashreporter.pages.UploadPanel$3.run(UploadPanel.java:158)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Cervator** [comment]
I wonder if we could put our own mini-pastebin somewhere on our infrastructure, locked down somehow to only be usable by the CR. Might help when the pastebin limit is hit, and could go a ways beyond that since it is just text so even high traffic shouldn't be that great a hit (unlike people trying to download game zips from Jenkins)

**Comment by msteiger** [comment]
Hosting that on terasology.org had a few advantages, I agree on that.

I thought about using ownCloud, but there's no proper Java library for managing that. An Android lib exists, but porting it to plain Java isn't straightforward, as it it's tied with Android's account management and networking system.

There's [Stikked](https://github.com/claudehohl/Stikked), which seems to be fairly popular, but we might need to adapt the code to suit that API.

**Comment by Cervator** [comment]
As usual it looks like there are all sorts of options out there. I didn't even realize hastebin is open source: https://github.com/seejohnrun/haste-server - its simplicity is nice. Written in node.js, isn't there something about being able to do more node/javascript stuff in general on Java 8?

Lots of options, little time :-)

**Comment by msteiger** [comment]
I've also been experimenting with [Apache Commons FileUpload](http://commons.apache.org/proper/commons-fileupload) and had it working in about 30min. A simplistic web-based upload form allows you to browse for files and upload them. The servlet runs on jetty and stores all incoming files in /tmp/upload.

If we add a very security checks (no 47GB BlueRay-Rips please!) and add (email) notifications, it could be a valuable alternative.

**Comment by Cervator** [comment]
Bump. Adding to this issue as it looks like pastebin uploading may either be broken or hitting the quota too readily these days. Reference support thread: http://forum.terasology.org/threads/delta-too-great.1374
