### ISSUE TITLE
NoSuchMethodError from Terasology escaped detail logging

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/CrashReporter#23]
Probably because it is an Error rather than an Exception? The error message was printed in the overview area fine but not not in the actual log file. No stacktrace either but maybe we can't access that right in an Error situation?

![clipboard_2015-11-10_16-25-23](https://cloud.githubusercontent.com/assets/1063833/11076233/b30b4d22-87c7-11e5-9e2e-4a6e68b4fee8.png)

Actual error was caused by a module being present in Omega 299 that hadn't been rebuilt after an engine change.

**Comment by msteiger** [comment]
I checked yesterday and the outermost try-catch clause catches `Throwable`, so I'm pretty sure it would be reported.

Where exactly did that happen? Do you still have a stacktrace?

**Comment by Cervator** [comment]
Easier to replicate now. Activate the latest "Sample" module and place a ReallyCrashGameBlock somewhere, `e` click it and boom. You get the error name alright, but that's it, the logging stops, no stacktrace (if one is even possible there).

In that case it is NoClassDefFoundError: java/io/PrintStream, due to the module sandboxing.

**Comment by Cervator** [comment]
Here's another tricky situation that seems related: Omega330 in Jenkins is bad as some of the module binaries are stale vs newer changes to Vector3i, resulted in the following errors *only if you ran the game from command line* with `java -jar ...`

The game stalled (as the chunk gen threads all died) but never technically crashed, and never output the following snippet when run directly from the exe. But you could see it fine running via jar.

```
00:24:11.683 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block AnotherWorldPlants:CypressBranch.0 with id 1065
00:24:11.736 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1870), capping to 1000
00:24:11.958 [Chunk-Generator-3] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:11.989 [Chunk-Generator-3] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1066
00:24:11.991 [Chunk-Generator-2] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:11.996 [Chunk-Generator-2] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1067
00:24:11.999 [Chunk-Generator-6] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.002 [Chunk-Generator-6] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1068
00:24:12.012 [Chunk-Generator-7] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.055 [Chunk-Generator-7] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1069
00:24:12.189 [Chunk-Generator-4] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.192 [Chunk-Generator-4] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1070
00:24:12.226 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.228 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1071
00:24:12.248 [Chunk-Generator-0] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.299 [Chunk-Generator-0] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1072
Exception in thread "Chunk-Generator-6" java.lang.NoSuchMethodError: org.terasology.world.chunks.CoreChunk.getBlock(Lorg/terasology/math/geom/Vector3i;)Lorg/ter
asology/world/block/Block;
        at org.terasology.gf.generator.GrowthBasedPlantSpawnDefinition.generatePlant(GrowthBasedPlantSpawnDefinition.java:76)
        at org.terasology.gf.generator.FloraFeatureGenerator.generateChunk(FloraFeatureGenerator.java:133)
        at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:66)
        at org.terasology.anotherWorld.PluggableWorldGenerator.createChunk(PluggableWorldGenerator.java:168)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:666)
        at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Chunk-Generator-3" java.lang.NoSuchMethodError: org.terasology.world.chunks.CoreChunk.getBlock(Lorg/terasology/math/geom/Vector3i;)Lorg/ter
asology/world/block/Block;
```

The log file remained entirely clueless, even when run via jar:

```
00:24:11.683 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block AnotherWorldPlants:CypressBranch.0 with id 1065
00:24:11.736 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1870), capping to 1000
00:24:11.958 [Chunk-Generator-3] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:11.989 [Chunk-Generator-3] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1066
00:24:11.991 [Chunk-Generator-2] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:11.996 [Chunk-Generator-2] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1067
00:24:11.999 [Chunk-Generator-6] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.002 [Chunk-Generator-6] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1068
00:24:12.012 [Chunk-Generator-7] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.055 [Chunk-Generator-7] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1069
00:24:12.189 [Chunk-Generator-4] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.192 [Chunk-Generator-4] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1070
00:24:12.226 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.228 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1071
00:24:12.248 [Chunk-Generator-0] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
00:24:12.299 [Chunk-Generator-0] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1072
00:26:08.321 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

I closed the window which is what prompted the log to get to the shut down stage, but the game process didn't dispose entirely.

**Comment by msteiger** [comment]
Exceptions that are thrown inside an executor service are not explicitly dealt with. The uncaught exception is forwarded to the default `UncaughtExceptionHandler`, which just prints the stack trace.

As a result, the threads die silently and game stalls while waiting for chunks.

Since the `LocalChunkProvider` is disposed only when leaving the game, it does not get disposed in that situation leaving the other thread pools alive.

**Comment by Cervator** [comment]
Awesome! With the `ReallyCrashGame` block from Sample I now get the CrashReporter catching and providing full details on resulting `java.lang.NoClassDefFoundError: java/io/PrintStream` ! Thanks so much :D

Is this resolved then, without any needed change in the CR?

**Comment by msteiger** [comment]
Yup, I think so.
