### ISSUE TITLE
CrashReporter gui not running when executing gradlew run command

### ISSUE THREAD

**Issue by mtjvankuik** [MovingBlocks/CrashReporter#29]
When i'm using the gradlew command ./gradlew run to run the gui for the CrashReporter, a stack trace of an example crash is given in the terminal. However, no gui application is starting whatsoever. This seems like to be broken. 

@rzats mentioned: Looks like that might have broken with the update that introduced subproject.

`MacBook-Pro-van-Martin-2:CrashReporter martinvankuik$ ./gradlew run
:CrashReporter-core:compileJava UP-TO-DATE
:CrashReporter-core:processResources UP-TO-DATE
:CrashReporter-core:classes UP-TO-DATE
:CrashReporter-core:compileTestJava
:CrashReporter-core:processTestResources UP-TO-DATE
:CrashReporter-core:testClasses
:CrashReporter-core:runInteractiveTest
ARGS: [setupForExtraLongMessageException, src/test/resources/lengthy_logfile.log, en-US]
INFO    500 - Method: setupForExtraLongMessageException [main] [org.terasology.crashreporter.InteractiveTestCases]
INFO    506 - Log file: src/test/resources/lengthy_logfile.log [main] [org.terasology.crashreporter.InteractiveTestCases]
INFO    506 - Log file: en-us [main] [org.terasology.crashreporter.InteractiveTestCases]
WARN    643 - An exception occurred [main] [org.terasology.crashreporter.InteractiveTestCases]
java.lang.RuntimeException: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus
        at org.terasology.crashreporter.InteractiveTestCases.main(InteractiveTestCases.java:62)
java.lang.reflect.InvocationTargetException
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
        at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
        at org.terasology.crashreporter.CrashReporter.report(CrashReporter.java:49)
        at org.terasology.crashreporter.InteractiveTestCases.main(InteractiveTestCases.java:69)
Caused by: java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at org.terasology.crashreporter.GlobalProperties.<init>(GlobalProperties.java:63)
        at org.terasology.crashreporter.CrashReporter$1.run(CrashReporter.java:59)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by mtjvankuik** [comment]
@Cervator I overheard that @msteiger is using Slack. Is it possible for me to get invited to contact msteiger who's the core maintainer?

**Comment by msteiger** [comment]
I'm surprised that it even work. CrashReporter is a library and should not "run" by itself. It looks like it triggers the unit tests. What exactly are you trying to achieve?

**Comment by mtjvankuik** [comment]
My mistake then, i thought it was a stand-alone tool which could be run by itself. What I need to do to run the crash reporter for Terasology. I'm using the IntelliJ IDEA and have already imported and cloned the Terasology and TerasologyLauncher projects.

**Comment by mtjvankuik** [comment]
close

**Comment by Cervator** [comment]
@mtjvankuik I went ahead and sent a Slack invite to your forum email address, let me know if you'd rather have it resent somewhere else. As you can see @msteiger also tends to be well-responsive here on GitHub :-)

@msteiger: I think the idea is about making it easier to develop with the CR. With Eclipse I figure you're able to set it up easily to where Terasology and the CR are in the same workspace, then when you build CR from source your Terasology picks up the change? 

I'm sure it is possible to get something similar working in IntelliJ. It reminded me of waaaay back when I got Jitter to work out of an embedded Terasology workspace as well as from an independent workspace (library style). There is even a `gradlew fetchLibX` task that'll grab our libs in source form, but only Jitter has/had the hook to automagically pick a source version if available, otherwise fall back to using the binary dependency.

I'm curious to get that working again/better. Ran out of time tonight (sorry @mtjvankuik!) after a longer design round than expected and some other bits of debugging. Will keep at it tomorrow. Any other tips or tricks would be appreciated I'm sure :-)

**Comment by Cervator** [comment]
Pinging @mtjvankuik here as a follow-up to the ping in my PR. You should be able to run CR in a Terasology source workspace now and see changes take effect immediately. I'm fishing for any kind of testing and review before merging :-)

**Comment by mtjvankuik** [comment]
@Cervator thanks for the heads up! If I have some time left i shall look
into it right away :')

2016-07-02 23:38 GMT+02:00 Rasmus Praestholm <notifications@github.com>:
